### ISSUE TITLE
[sld-parser] Allow one-line SLD string as return element of writeStyle

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#1040]
### Description:
Currently the `writeStyle(...)` function of the SLD-Parser returns a prettified SLD / XML string with whitespaces and linebreaks. This is very useful since it is human-readable. For some use-cases it would be more handy to get the XML as one-liner. Since changing the `writeStyle` definition would change the interface I'd suggest to add a configuration option to the parser itself.

Any thoughts on this? TIA!

**Comment by KaiVolland** [comment]
This would be a nice enhancement. Would be nice if you could provide a PR.
