### ISSUE TITLE
broken link on documentation

### ISSUE THREAD

**Issue by pvgenuchten** [terrestris/geostyler#1134]
### Description:
On the documentation [index page](https://terrestris.github.io/geostyler/latest/index.html#introduction) the link to [geostyler docs](https://terrestris.github.io/geostyler/styleguide/) is broken

![image](https://user-images.githubusercontent.com/299829/61030467-b6a62900-a3bd-11e9-8c83-98249aa72b56.png)

**Comment by KaiVolland** [comment]
@pvgenuchten Thx for contributing.

Seems like the real problem is, that the documentation didn't update since: https://github.com/terrestris/geostyler/commit/4c7d758064b5e428a45208785d1d87e2269301bb

I'll have a look at it.

**Comment by chrismayer** [comment]
Hi @KaiVolland, are there any news on this?

**Comment by KaiVolland** [comment]
I tried to fix this with #1138. But it didn't help. Seems like there is still something wrong with the CI.

**Comment by chrismayer** [comment]
Thanks for the feedback @KaiVolland. Please ping me if I can support you somehow.

**Comment by dnlkoch** [comment]
Automatic update of the `gh-pages` has been fixes by #1155. I'll close this issue as the described bug should be resolved by now. 

Please note #1158.
