### ISSUE TITLE
Basic UI for RasterSymbolizer / ColorMap

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#1136]
### Description:
A basic UI to take advantage of the `RasterSymbolizer` would be a good thing IMHO to put things forward. 
I suggest to start with a simple UI to let the user create and manipulate a `ColorMap`. Maybe we can re-use several components of the classification dialog for vector data or am I wrong?

I created a (very quick and dirty) UI sketch as discussion base:

![grafik](https://user-images.githubusercontent.com/1185547/61039626-6afc7b00-a3cf-11e9-840b-e57028d111e6.png)

As always: Improving / extending the UI at later points should not be the problem due to the micro-component based architecture.  For example adding a `RasterCalculator` (see #935).

**Comment by KaiVolland** [comment]
@jansule did this already.

![terrestris github io_geostyler-demo_](https://user-images.githubusercontent.com/1849416/61047455-cfbfd180-a3df-11e9-9442-3d5f1a40c37c.png)

It's in the demo app.

**Comment by chrismayer** [comment]
:heart_eyes: Awesome! Wasn't aware of this.

So what is needed to get advanced styling possibilities based on concrete raster data is a data connection by GeoTiff (#992) or WCS (#1137).
