### ISSUE TITLE
Version package.json not in sync with version tag

### ISSUE THREAD

**Issue by jansule** [terrestris/geostyler#1146]
### Description:

The latest release is `4.2.0` but the [package.json](https://github.com/terrestris/geostyler/blob/62206cf8e0c63fd3e55b3939f591d32def89864b/package.json#L3) still shows `4.1.4`.

**Comment by chrismayer** [comment]
Not sure what went wrong. Normally done by the `np` tool executed via `npm run release`. I'll have a look.

**Comment by chrismayer** [comment]
Should be OK with [Version 4.2.1](https://github.com/terrestris/geostyler/releases/tag/v4.2.1)

**Comment by marcjansen** [comment]
Thanks for the quick and appropriate fix

**Comment by jansule** [comment]
@marcjansen same problem again (now `4.2.2` vs `4.2.1`). Did you pull tags before releasing?

**Comment by marcjansen** [comment]
I did...

**Comment by marcjansen** [comment]
... also it is in sync now, isn't it?

**Comment by chrismayer** [comment]
The package.json in the master branch seems correct now, but in the [archive of the 4.2.2 release](https://github.com/terrestris/geostyler/archive/v4.2.2.zip) the version in the package.json is `4.2.1`.

**Comment by chrismayer** [comment]
For me the problem was that the `np` script stopped too early due to connection problems with github for the push of the version bump. Thus the version bump commit was only in my local repo and I had to push it manually before I then could do the release in the github repo.

**Comment by marcjansen** [comment]
Is it possible that `np` pushes the commit and the tag to `origin` only? For my setup this is my fork, not the one real repo?

**Comment by dnlkoch** [comment]
With the current release (`4.3.0`) the issue seems to be resolved. Or did you encounter some problems during the release @chrismayer?

**Comment by chrismayer** [comment]
Nope, no problems during the release process. I'll close this. Please re-open if there are any problems in the future.
