### ISSUE TITLE
Add UI tool to clone a rule in RuleTable

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#1150]
### Description:
A tool to clone an existing rule in the `RuleTable` would be a nice improvement. Users can start new rules on existing ones. This can be important in case of having complex symbolizers and/or filters.

Suggestion: Another button `Clone Rule` in the bottom bar of the `RuleTable` UI, which clones all selected rows (by checkbox).

**Comment by jansule** [comment]
We should keep in mind that we also have an alternative layout to the `RuleTable`. IMO cloning rules should also be applicable there.

**Comment by chrismayer** [comment]
Correct, if we want to have it, it should not be a problem to integrate this in the non-compact layout/view.
