### ISSUE TITLE
[geostyler-style] Add 'format' parameter to IconSymbolizer

### ISSUE THREAD

**Issue by weskamm** [terrestris/geostyler#122]
It would be useful to have an `format` property on the IconSymbolier.
The background is when handling SLDs with `ExternalGraphics`, these do have a mandatory `format` parameter (which hold a value like `image/png`), which needs to be preserved while transforming / parsing.

I can provide a PR if this is a wanted feature

**Comment by jansule** [comment]
geostyler-sld-parser parses the format of a property since PR https://github.com/terrestris/geostyler-sld-parser/pull/72. The UI should not be affected by this, since the format can be parsed from the file extension. 

-> closing this issue
