### ISSUE TITLE
[geostyler-sld-parser] Several issues causing SLD validation to fail

### ISSUE THREAD

**Issue by weskamm** [terrestris/geostyler#123]
The SLD output currently produced by the sld-parser is invalid for several reasons:

* The ogc namespace is missing on Filters and Properties
* The order of ScaleDenominator, Filter and Symbolizer is invalid, e.g. the symbolizer has to appear after the ScaleDenominators
* Some Filters may have invalid output, e.g. using an empty, selfclosing Literal for values

I will try to fix these and other problems that will come along.

**Comment by KaiVolland** [comment]
Can this be closed? https://github.com/terrestris/geostyler-sld-parser/pull/16 is merged...

**Comment by weskamm** [comment]
Yes, if new problems arise, they can be fixed seperately
