### ISSUE TITLE
ComparisonFilter GUI: Filter attributes in AttributeCombo by blacklist or filter function

### ISSUE THREAD

**Issue by ahennr** [terrestris/geostyler#135]
Sometimes it might be wanted that only filterable attributes are shown in the `ComparisonFilter GUI`. For example, the geometry attribute or attributes in a blacklist should not be selectable.
Should this be covered here or is this rather a project specific behaviour?

**Comment by marcjansen** [comment]
I'd vote for an optional filter function. This is a very common requirement, I guess. Thanks for the input

**Comment by chrismayer** [comment]
This is an important point. Since a filter function is a proven concept in many frameworks, I 'd also vote for this.

**Comment by KaiVolland** [comment]
Filter functions are always a nice option.

**Comment by ahennr** [comment]
Done, see #142
