### ISSUE TITLE
Create missing UI Components for Symbolizer Editor

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#160]
Currently the `Symbolizer` editor only supports `Symbolizer`s of kind `circle`.

We need to create the editors for for the other `Symbolizer`s:
1. - [x] General `Select` field for Symbolizer kind
2. - [ ] `IconEditor`
3. - [x] `TextEditor`
4. - [x] `LineEditor`
5. - [x] `FillEditor`

We should make use of the existing `Field`s and add new ones if necessary.

**Comment by chrismayer** [comment]
I am tackling the ``LineEditor`` at the moment.

**Comment by KaiVolland** [comment]
We also need a general `Select` field or similiar to determine what style we want to create. The options should be limited to what makes sense for the `type` of the current GeoStyler Style.type.

**Comment by chrismayer** [comment]
FillEditor done in #181 (under review).

**Comment by chrismayer** [comment]
TextEditor done in #185 (under review).

**Comment by KaiVolland** [comment]
I'll tackel the "General Select field for Symbolizer kind"

**Comment by KaiVolland** [comment]
`KindField` done in #190 (under review)

**Comment by KaiVolland** [comment]
I'll tackle the `IconEditor` now.
