### ISSUE TITLE
Validation enhancements / bugs

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#182]
1. The validation of the `ComparisonFilter` is wrong when constructed with a filter.
![localhost_3000_ 8](https://user-images.githubusercontent.com/1849416/41337596-f46e87f4-6eef-11e8-8dbe-1d78cec7ec7f.png)

Possible fix (line 132):
```javascript
validateStatus: {
  attribute: attrName ? 'success' : 'error',
  operator: filter[0] ? 'success' : 'error',
  value: filter[2] ? 'success' : 'error'
}
```

2. A Textfilter-Comparison against empty string `""` or `null` should not be marked as invalid.

![image](https://user-images.githubusercontent.com/1849416/41337649-17e254a4-6ef0-11e8-856f-5d7fd7d6cddb.png)

**Comment by ahennr** [comment]
Fixed in https://github.com/terrestris/geostyler/pull/186
