### ISSUE TITLE
[geostyler-openlayers-parser] Enable Travis and Coveralls

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#192]
We need to enable Travis CI and Coveralls for the [geostyler-openlayers-parser](https://github.com/terrestris/geostyler-openlayers-parser)

**Comment by jansule** [comment]
@KaiVolland can this issue be closed? Travis and Coveralls were integrated with https://github.com/terrestris/geostyler-openlayers-parser/commit/6b5da8c9d66e1d9acec7c39d177be36be4713b81.

**Comment by KaiVolland** [comment]
Yes.
