### ISSUE TITLE
Support various well known symbols

### ISSUE THREAD

**Issue by marcjansen** [terrestris/geostyler#241]
It'd be nice if we could easily use stars, square, points, triangles and so on for styling points.

**Comment by chrismayer** [comment]
From my understanding this needs several things:

  - Extend the `IconSymbolizer` UI to allow to pick a Well-Known-Symbol
  - Extent the [geostyler-openlayers-parser](https://github.com/terrestris/geostyler-openlayers-parser   ) so it can handle Well-Known-Symbols (like done [here](https://openlayers.org/en/latest/examples/earthquake-custom-symbol.html) )
  - Extent the [geostyler-sld-parser](https://github.com/terrestris/geostyler-sld-parser) so it can handle Well-Known-Symbols

**Comment by jansule** [comment]
Was done in https://github.com/terrestris/geostyler/pull/337 and https://github.com/terrestris/geostyler/pull/374 as well as in the parsers linked in mentioned PRs.

Closing issue.
