### ISSUE TITLE
Loosing vertical scrollbar when changing Symbolizer

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#245]
The app looses the vertical scrollbar when the the Symbolizer Kind is changed in the UI. So not all Symbolizer form fields are accessible.

Steps to reproduce:

  - Start the GeoStyler app
  - Hit `Edit Symbolizer`
  - Change `Kind` to `Icon`

**Comment by jansule** [comment]
A current workaround is the introduction of EditorWindow in #440. But the core problem still remains.

**Comment by KaiVolland** [comment]
As it is currently not an issue any more i'll close this. Reopen if needed.
