### ISSUE TITLE
[geostyler-style] Add support for multiple symbolizers

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#248]
Currently a `Rule` can have exactly one Symbolizer. This should be enhanced so a Rule can have one or more symbolizers.

**Comment by KaiVolland** [comment]
Somewhat duplicate of https://github.com/terrestris/geostyler/issues/85 but it targets the Style here.

**Comment by chrismayer** [comment]
> Somewhat duplicate of #85 but it targets the Style here.

Right...I change the title of #85 so it becomes clearer that is is related to the SLD-Parser (whereas this is related to geostyler-style).

**Comment by KaiVolland** [comment]
Solved with #332
