### ISSUE TITLE
Raise z-index of class gs-symbolizer-editor

### ISSUE THREAD

**Issue by jansule** [terrestris/geostyler#273]
The z-index of class `.gs-symbolizer-editor` should be raised at least to `2`. Otherwise buttons will overlap the editor, as can be seen in following image (see `Text-Opacity` field).

![grafik](https://user-images.githubusercontent.com/12186477/42503274-99293bd8-8438-11e8-8826-f7c08c3c0307.png)

Here, with `z-index: 2`:

![grafik](https://user-images.githubusercontent.com/12186477/42503649-81e398be-8439-11e8-842c-a1968cb409c9.png)

**Comment by marcjansen** [comment]
Awesome! Thx for this. I am 👍 but others should weigh in here.

**Comment by KaiVolland** [comment]
IMHO we should show the Symbolizer-Editor in a window-like component anyway. We could think about using the `window` of `react-geo` or directly react-rnd.

**Comment by KaiVolland** [comment]
Solved with #440
