### ISSUE TITLE
Geostyler-Style Type Definition unnecessary property

### ISSUE THREAD

**Issue by jansule** [terrestris/geostyler#303]
At the moment, I am implementing the feature of handling multiple symbolizers within one rule. Accordingly, I am updating the [geostyler-style](https://github.com/terrestris/geostyler-style) and the parsers.

I was wondering if the `type` property of `Style` (see [here](https://github.com/terrestris/geostyler-style/blob/master/index.d.ts#L239)) is of any particular use. <del>So far, it looks like the parsers set this attribute according to the kind of the used symbolizer, **but the property is not being used at all within the GUI**</del>. E.g. the matching symbolizer editor will be handled based on the `kind` property of type `Symbolizer`. 

So, I propose to remove this property within my upcoming PR.

@chrismayer could you please enlighten me, if I miss anything here?

PS: Sorry, for posting this here, even though it is clearly a `geostyler-style` issue, but there is no issue board on the `geostyler-style` repo. 

**Edit:** The property is being used in the GUI, but IMHO could be replaced easily with already existing properties.

**Comment by jansule** [comment]
Talked to @dnlkoch a few minutes ago.

Following the sld specification, a Rule can have multiple Symbolizers of any kind. This will be possible in geostyler with the upcoming PRs. Thus, if we follow the sld specification, there is no need to distinguish the type of a Style. 

However, if we want to restrict this a little more (e.g. no  PointSymbolizer in a Polygon), then this property will be useful.

I see the main problem in detecting the type of a Style within the parsers. Right now, the type of a Style will be detected based on the Symbolizer in the first Rule (only one Symbolizer possible at this point). This might lead to problems, since this Symbolizer is not necessarily equivalent to the feature type. 

_Example_: A polygon should have the type `Fill`. But it might only have a LineSymbolizer or TextSymbolizer defined. This would lead to setting the type to `Line` or `Line`. 

Until we don't find a robust way to detect the type of a Style, I am going to remove the property.

**Comment by hwbllmnn** [comment]
:+1 Also, a feature type is not necessarily limited to one geometry type but may very well include geometries of all kinds.
