### ISSUE TITLE
Fix interface inheritance in geostyler-style

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#31]
Currently this is a correct implementation but it shouldn't be valid:
We have to find a way to restrict mixed properties.

```typescript
interface Symbolizer {
    visibility?: boolean
}

interface PointSymbolizer extends Symbolizer {
    radius: number
}

interface LineSymbolizer extends Symbolizer {
    lineWidth: number
}

const myRide: PointSymbolizer | LineSymbolizer = {
    visibility: true,
    // Just one of both should be allowed. Not mixed.
    radius: 5,
    lineWidth: 10
}
```

**Comment by marcjansen** [comment]
> Union types can be a bit tricky here, but it just takes a bit of intuition to get used to. If a value has the type A | B, we only know for certain that it has members that both A and B have. 

… from http://www.typescriptlang.org/docs/handbook/advanced-types.html

That page has some details how to get around this, but I fear we might have to accept this isn't easily possible. We might want to introduce some property `kind` or `type` (which is required), taht can make code paths further down the orad easier to read. Especially together with `--strictNullChecks` or 

```typescript
function assertNever(x: never): never {
    throw new Error("Unexpected object: " + x);
}
// the use it when we are e.g. switching depending on the kind
```

(also from that page)

**Comment by marcjansen** [comment]
An example for the kind property: https://blog.mariusschulz.com/2016/11/03/typescript-2-0-tagged-union-types

**Comment by chrismayer** [comment]
> We might want to introduce some property kind or type (which is required), taht can make code paths further down the orad easier to read.

Maybe we can avoid an additional ``kind`` property by using ``instanceof`` (see http://www.typescriptlang.org/docs/handbook/advanced-types.html)

**Comment by KaiVolland** [comment]
The style representation is know available in its own repository: https://github.com/terrestris/geostyler-style

The Inheritance problem was solved with the `kind`-property solution.
