### ISSUE TITLE
[SLD-Parser] Error when TextSymbolizer with empty Field property

### ISSUE THREAD

**Issue by jansule** [terrestris/geostyler#317]
When parsing TextSymbolizer with no specified properties, an error is thrown. TextSymbolizer requires input for the `Field` property.

Steps to reproduce:
1. Select `Text` in Symbolizer Kind
2. In Code Editor switch `Format` from `Geostyler Style` to `SLD Style Parser`

**Comment by KaiVolland** [comment]
This issues seems to be solved.
