### ISSUE TITLE
[INFO] Working with npm link

### ISSUE THREAD

**Issue by jansule** [terrestris/geostyler#318]
When developing multiple packages at once, using `npm link` is very helpful. However, when a linked package has the same dependency as the linking package, npm does not resolve dependencies very well. This might lead to unexpected errors, because multiple instances of the same dependency exist. In our case this might happen with openlayers, which is being used in `geostyler` and `geostyler-openlayers-parser`.

To counteract this problem, an alias can be defined in `geostyler`. To do so in `geostyler/node_modules/react-scripts-ts/config/webpack.config.dev.js` following line needs to be added:

```
(Line 118): 'ol': path.join(__dirname, '../..', 'ol')
```

**Comment by marcjansen** [comment]
Good to know. Can you move this info to the readme or a file called DEVELOPMENT.md or sth. like that and create a PR, please?
