### ISSUE TITLE
Symbolizer missing default values

### ISSUE THREAD

**Issue by jansule** [terrestris/geostyler#327]
Many fields in the Symbolizer do not provide default values. This leads to crashing the page, when changing to SLD parser.

Steps to reproduce:
1. Select `SLD Style Parser` in CodeEditor
2. Open Symbolizer and set `kind` to `Fill`
3. Add number into `Fill Opacity` field
4. Remove number from `Fill Opacity` field
5. Watch page crashing

This error occurs with following fields:
- Fill -> Fill Opacity
- Line -> Width
- Line -> Opacity
- Line -> Dash Offset
- Text -> Field ([see also #317 ](https://github.com/terrestris/geostyler/issues/317))
- Text -> Text Size

**Comment by KaiVolland** [comment]
The page is not crashing anymore, but the UI, Style and Preview still differ when adding a new `Rule`/`Symbolizer`.
We have to think about general default values. This is maybe related to #217.
