### ISSUE TITLE
Deleting one symbolizer from a rule removes all but one symbolizer in example UI

### ISSUE THREAD

**Issue by marcjansen** [terrestris/geostyler#346]
Steps to reproduce

* Go to https://terrestris.github.io/geostyler/
* Click `Edit Symbolizer`
* Click the `+` multiple times until you have 4 symbolizers
* Delete any of the symbolizers by clicking on `x`

Expected result:
* All other symbolizers remain in UI and the generated output

Actual result
* All but one symbolizer vanish from the UI and the output

**Comment by chrismayer** [comment]
Only occurs if no changes were made to the symbolizer. Setting a property, e.g. radius, will prevent the deletion.

**Comment by marcjansen** [comment]
Thanks for the clarification, what does clicking plus do? is it maybe passing refernces instead of cloning / recreating from scratch? wild guess of course.

**Comment by jansule** [comment]
There is a problem finding out which symbolizer should be removed when clicking on `x`, since symbolizer is lacking some kind of ID or unique property. Right now, I am assuming that all symbolizers are somehow distinct and remove the symbolizer(s) where all properties are equal to the one on which the `x` was clicked.

Rule, on the other hand, has the unique property `name` which can be used as identifier. So this problem does not occur there.

We could add an identifier to the definition of symbolizer to avoid this problem, but IMHO this would add a property which only solves a technical problem and does not really belong to the concept of a symbolizer.

**Comment by marcjansen** [comment]
I faintly remember a comment somewhere in the geostyler, where an id is generated (rules maybe?) and used for the exact same reason. @kaivolland added it, and also a TODO comment. I am not sure if this actualy used, but I recently stumbled over this.

**Comment by jansule** [comment]
You can find the comment [here in Style.tsx](https://github.com/terrestris/geostyler/blob/370c54395e224f4886cf2d71507ca65872d52be3/src/Component/Style/Style.tsx#L135-L179). Please also notice the corresponding TODO comment in the addSymbolizer function.

```javascript
addRule = () => {
    const style = _cloneDeep(this.state.style);
    // TODO We need to ensure that rule names are unique
    const randomId = Math.floor(Math.random() * 10000);
    const newRule: GsRule = {
      name: 'rule_' + randomId,
      symbolizer: [this.getDefaultSymbolizer(_get(style, 'rules[0].symbolizer[0]'))]
    };
    style.rules = [...style.rules, newRule];
    if (this.props.onStyleChange) {
      this.props.onStyleChange(style);
    }
    this.setState({style});
  }

  removeRule = (rule: GsRule) => {
    const style = _cloneDeep(this.state.style);
    const newRules = style.rules.filter((r: any) => r.name !== rule.name);
    style.rules = newRules;
    if (this.props.onStyleChange) {
      this.props.onStyleChange(style);
    }
    this.setState({style});
  }

  addSymbolizer = (rule: GsRule) => {
    const style = _cloneDeep(this.state.style);
    // TODO generate some kind of id
    // right now, all properties of symbolizer must match
    let newSymbolizer: GsSymbolizer = this.getDefaultSymbolizer(_get(rule, 'symbolizer[0]'));
    const ruleIdx = style.rules.findIndex((r: GsRule) => r.name === rule.name);
    if (ruleIdx > -1) {
      style.rules[ruleIdx].symbolizer.push(newSymbolizer);
      if (this.props.onStyleChange) {
        this.props.onStyleChange(style);
      }
      this.setState({style});
    }
  }

  removeSymbolizer = (rule: GsRule, symbolizer: GsSymbolizer) => {
    const style = _cloneDeep(this.state.style);
    const ruleIdx = style.rules.findIndex((r: GsRule) => r.name === rule.name);
    // if all properties of a symbolizer are equal, remove this symbolizer
    const newSymbolizers = style.rules[ruleIdx].symbolizer
      .filter((symb: GsSymbolizer) => !_isEqual(symb, symbolizer));
    style.rules[ruleIdx].symbolizer = newSymbolizers;
    if (this.props.onStyleChange) {
      this.props.onStyleChange(style);
    }
    this.setState({style});
  }
```

**Comment by KaiVolland** [comment]
Should be solved with the introduction of the `EditorWindow`.
