### ISSUE TITLE
Symbolizer GUI not fully visible

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#355]
The GUI for editing a Symbolizer is not fully visible. The lower part is cut off.

With zoom 100%:
![image](https://user-images.githubusercontent.com/1185547/44198515-f0d16100-a141-11e8-9d74-6c12178dd295.png)

With zoom 90% (see the prev. missing field Stroke-Opacity):  
![image](https://user-images.githubusercontent.com/1185547/44198534-fb8bf600-a141-11e8-9252-913893f38e59.png)

Tested with Firefox 61.

**Comment by jansule** [comment]
Looks like the footer overlaps the lower part.

![image](https://user-images.githubusercontent.com/12186477/44255409-4f601300-a206-11e8-8ef1-a843ece11d29.png)

**Comment by KaiVolland** [comment]
The symbolizer editing should be moved to some kind of window ui anyway.

**Comment by KaiVolland** [comment]
Solved with introduction of SymobilizerWindow.
