### ISSUE TITLE
Make read and write methods of Data- and StyleParsers async

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#40]
The read and write methods of Data- and StyleParsers should be asynchornous / return Promises.

This allows us to do asynchronous stuff in the concrete implementations of our parsers. An explicit example would be the (not yet existing) WFS-Dataparser which needs to do a request before it is able to read the data.

**Comment by chrismayer** [comment]
The part for the DataParser is addressed in #34. So I pass the baton to @KaiVolland.

**Comment by KaiVolland** [comment]
Solved with https://github.com/terrestris/geostyler-style/pull/3
