### ISSUE TITLE
Publish code over at npm

### ISSUE THREAD

**Issue by marcjansen** [terrestris/geostyler#41]
The code should be published over at npm, also of the utility libraries. I suggest `geostyler`, right now that name is not taken, take `@terrestris/geostyler` otherwise.

Publishing should be made a simple npm task, e.g. using [`np`](https://www.npmjs.com/package/np),  [`publish-please`](https://www.npmjs.com/package/publish-please), [`release-it`](https://www.npmjs.com/package/release-it) or sth. more elaborated like [`semantic-release`](https://www.npmjs.com/package/semantic-release). The latter requires some change in how we name our commits.

Anyhow, this should all live at npm.

**Comment by marcjansen** [comment]
> I suggest to use semantic versioning once we published.

I agree

**Comment by KaiVolland** [comment]
All packages are now on npm. Compare [Readme](https://github.com/terrestris/geostyler/blob/master/README.md)
