### ISSUE TITLE
GeoStyler as browser library

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#419]
To use the `GeoStyler` components outside of an react application (from the npm universe) we need to do a seperate build.
As we did create the project with `create-react-app-typescript` we are stuck to WebPack v3. 

#413 does export the GeoStyler as a browser compatible library but breaks the regular build (WebPack v4).

So a solution is needed to bundle the tsx and css files with the current setup.
Alternatively we could 'eject' `GeoStyler`...

Any ideas @terrestris/devs ?

**Comment by marcjansen** [comment]
If we eject, we can upgrade to webpack >= 4, right? and then using this elsewhere is no problem?

Do we have any chance to push create-react-app-typescript to ise v4 of webpack?

**Comment by KaiVolland** [comment]
The author will update to webpack v4 when create-react-app v2 is released which is currently in alpha:
https://github.com/wmonk/create-react-app-typescript/issues/331

**Comment by dnlkoch** [comment]
Any chance to downgrade your changes proposed in #413 to webpack v3?
