### ISSUE TITLE
To eject or not eject – That is the question

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#526]
We're more and more getting problems due to the CRA (Create-React-App) setup.

1. Currently there is no (clean) way to include a CSS preprocessor like LESS. #65 
2. Updating devdependencies like webpack, jest, react-styleguidist relies to CRA. This is can be sometimes blocking.
3. It feels like a blackbox.

**Comment by jansule** [comment]
Just as an example: Currently, we cannot update webpack to version 4 because react-scripts-ts depends on webpack 3 (#489). This also blocks update of styleguidist (#510).

**Comment by chrismayer** [comment]
I am not too deep into the CRA topic but the points listed above by @KaiVolland give me the feeling that it would be better to eject. Maybe the eject with a proper and complete documentation won't be that problematic?

**Comment by KaiVolland** [comment]
Ejecting is simple and just leaves us some config files (webpack, babel, etc.) that can be shrinked afterwards by removing some uneeded configs. Shouldn't be a problem at all and IMHO meanwhile the benefits of the flexibility might outwheigh the comfort of CRA.

**Comment by KaiVolland** [comment]
I'll giv it a try.

**Comment by KaiVolland** [comment]
I ejected an ran into some problems when building.
I pushed the current state: https://github.com/KaiVolland/geostyler/tree/eject but as the priority is not THAT high... I'll skip this for know.

![https://thumbs.gfycat.com/NecessaryCourteousFalcon-size_restricted.gif](https://thumbs.gfycat.com/NecessaryCourteousFalcon-size_restricted.gif)

**Comment by jansule** [comment]
Currently, I am moving the demo application into a dedicated repo [geostyler-demo](https://github.com/terrestris/geostyler-demo) to make a clear distinction between the library and the demo application. Through this, we can completely remove CRA from this repo and handle it the same way as we handle react-geo. Thus, we do not have to think about whether to eject or not.

The problems with CRA will then not affect geostyler anymore.

**Comment by KaiVolland** [comment]
I think this process is finished. Reopen if im wrong.
