### ISSUE TITLE
Broken CSS in Filter

### ISSUE THREAD

**Issue by jansule** [terrestris/geostyler#545]
CSS in filter needs to be fixed. Currently it looks like this:

![image](https://user-images.githubusercontent.com/12186477/48065396-d8199a00-e1ca-11e8-90aa-7d463b004994.png)

**Comment by jansule** [comment]
In the current version, the css looks good again. Might have been fixed by antd.
-> Closing this issue

**Comment by KaiVolland** [comment]
Should be fixed in #624

**Comment by jansule** [comment]
Nope. You are right. It is fixed. Even though I just pulled the new master half an hour ago, the changes were not visible for me. Might be a cache thing. Closing this again.
