### ISSUE TITLE
Create geostyler-wfs-parser

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#56]
Create the ``geostyler-wfs-parser`` repository under terrestris.

It should contain the concrete implementation of the GeoStyler_DataParser interface targeting WFS based geodata.

**Comment by KaiVolland** [comment]
Hi @ahennr as i know that you'll need this for a project i assigned this issue to you. :wave:

**Comment by ahennr** [comment]
See [here](https://github.com/terrestris/geostyler-wfs-parser)

**Comment by KaiVolland** [comment]
I'll close this as done.
