### ISSUE TITLE
Refactor DataProvider & ParserDesc

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#571]
The DataParser should be modified to act more like the parsing of a `Style`.

Therfore we should make use of the `DataParserConstructable` interface from 'geostyler-style'.

**Comment by chrismayer** [comment]
> The DataParser should be modified to act more like the parsing of a `Style`

Can you specify this a bit more,  @KaiVolland? TIA!

**Comment by KaiVolland** [comment]
It's about choosing/setting the Parser in the DataProvider.

I think that we should make use of the `DataParserConstructable` in the `DataProvider`.
Almost like we do with the `StyleParserConstructable` in the `StyleLoader`.

This way the `ParserDesc` would become obsolete and the code would be less diverse.

**Comment by KaiVolland** [comment]
The `DataParserConstructable` and `StyleParserConstructable` have been removed so this issue is not relevant any more.
