### ISSUE TITLE
Comparison Filter GUI

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#58]
Setup the UserInterface for `ComparisonFilters`.

The final UI for the filter should look something like this:

![188 40 113 28_momo_admin_](https://user-images.githubusercontent.com/1849416/40056422-ab95dcfe-584b-11e8-98f9-091823107cfd.png)

It consists of three key components:
1. An "AttributeCombo" which reads the available attributes from the `DataParser`
2. An "OpertatorCombo" to select one of the Opertors allowed by the `Style`-[`ComparisonFilter`](https://github.com/terrestris/geostyler-style/blob/master/index.d.ts#L20).
3. A "ValueField" which is related to the datatype of the selected attribute.

_____
:exclamation: Please keep in mind that we will have `NegationFilter` and `CombinationFilter` later on. So the filters might be nested.

Component naming and visualization is not fixed. Just choose the best matching UI-Component from [Ant Design components](https://ant.design/docs/react/introduce).

**Comment by chrismayer** [comment]
Done by #64
