### ISSUE TITLE
Enable less or similar for advanced styling

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#65]
We should integrate a CSS Preprocessor such as less to get advanced styling possibilities.

See: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc

**Comment by KaiVolland** [comment]
I don't like the approach recommende by create-react-app as linked above. This would lead to build files (css) inside the module-folders.
We could think about ejecting (and getting rid of CRA completly).

**Comment by jansule** [comment]
As soon as we got rid of CRA, adding a CSS preprocessor should not be a problem. Little more info in #526
