### ISSUE TITLE
Design GeoStyler_Data model and interface

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#7]
We need to design the `GeoStyler_Data` (naming is not fixed) model.

It should be able to represent and describe the attributes of a vectordata dataset.

It could somewhat look like:
```javascript
{
  "attributes": [{
    "name": "firstname",
    "type": "String",
    …
  }, {
    "name": "age",
    "type": "Number",
  }, …],
  "data": [{
    "name": "Peter",
    "age": 12
  }, {
    "name": "Ilse",
    "age": 13
  }, …]
}
```

**Comment by chrismayer** [comment]
Since we have our model available in a separate [repository](https://github.com/terrestris/geostyler-data), this will be closed now.
