### ISSUE TITLE
Integrate OpenLayers with TypeScript

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#83]
For several components, such as the style preview UI (see #81) and the preview map inside the ``StyleEditor`` (see #82) we need the integration of OpenLayers. Since we are using TypeScript we need some kind of TypeScript-binding for OpenLayers. Yet there is no official support for this but [here](https://github.com/openlayers/openlayers/issues/8120) can be found some ideas and infos.

**Comment by chrismayer** [comment]
I suggest using the OL Type Definitions here: 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ol 

What do you think @KaiVolland ?

**Comment by KaiVolland** [comment]
DefinitelyTyped is definitely the best source for types. :wink:
