### ISSUE TITLE
Parser does not recognize 'fill-opacity' parameter for PointSymbolizer

### ISSUE THREAD

**Issue by NeliHarbuzava** [terrestris/geostyler#915]
### Description:
The SLD Cookbook gives an example of Triangle PointSymbolizer with 'fill-opacity' parameter. But `new SLDParser().readStyle()` method does not recognize 'fill-opacity' and returns response without it. Example SLD (Source https://docs.geoserver.org/stable/en/user/styling/sld/cookbook/points.html#transparent-triangle)
```
<?xml version="1.0" encoding="UTF-8"?>
<sld:StyledLayerDescriptor
	xmlns="http://www.opengis.net/sld"
	xmlns:sld="http://www.opengis.net/sld"
	xmlns:gml="http://www.opengis.net/gml"
	xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0">
	<sld:NamedLayer>
		<sld:Name>Default Styler</sld:Name>
		<sld:UserStyle>
			<sld:Name>Default Styler</sld:Name>
			<sld:Title>Accidents</sld:Title>
			<FeatureTypeStyle>
                          <Rule>
                            <PointSymbolizer>
                                <Graphic>
                                   <Mark>
                                     <WellKnownName>triangle</WellKnownName>
                                     <Fill>
                                         <CssParameter name="fill">#009900</CssParameter>
                                         <CssParameter name="fill-opacity">0.2</CssParameter>
                                    </Fill>
                                    <Stroke>
                                       <CssParameter name="stroke">#000000</CssParameter>
                                       <CssParameter name="stroke-width">2</CssParameter>
                                    </Stroke>
                                </Mark>
                                <Size>12</Size>
                              </Graphic>
                            </PointSymbolizer>
                         </Rule>
                       </FeatureTypeStyle>
		</sld:UserStyle>
	</sld:NamedLayer>
</sld:StyledLayerDescriptor>
```

`await new SLDParser().readStyle()` response:
```
{
  "name": "Accidents",
  "rules": [
    {
      "name": "",
      "symbolizers": [
        {
          "kind": "Mark",
          "color": "#009900",
          "radius": 6,
          "wellKnownName": "Triangle",
          "strokeColor": "#000000",
          "strokeWidth": 2
        }
      ]
    }
  ]
}
```

I checked **./src/SldStyleParser.ts** file and found that `getMarkSymbolizerFromSldSymbolizer()` method creates `fillParams` variable (line 271) but does not use 'fill-opacity' in the response.

**Comment by marcjansen** [comment]
Thanks for the report. I have assigned @KaiVolland and @jansule, hopefully they'll have an idea.

**Comment by KaiVolland** [comment]
I just left some comments at the PR.

**Comment by chrismayer** [comment]
This issue is still a TODO, right? I am asking because the linked PR has been closed.

I discovered the following: Not just `new SLDParser().readStyle()` does not recognize the the `fill-opacity`. Also `new SLDParser().writeStyle` does not give the correct output. A rule with a transparent mark / symbol will be returned in SLD as

```xml
       <sld:Rule>
          <sld:Name>rule_480</sld:Name>
          <sld:PointSymbolizer>
            <sld:Graphic>
              <sld:Mark>
                <sld:WellKnownName>circle</sld:WellKnownName>
                <sld:Fill>
                  <sld:CssParameter name="fill">#0E1058</sld:CssParameter>
                </sld:Fill>
              </sld:Mark>
              <sld:Opacity>0.25</sld:Opacity>
            </sld:Graphic>
          </sld:PointSymbolizer>
        </sld:Rule>
```
The line 

`<sld:Opacity>0.25</sld:Opacity> `

should be 

`<sld:CssParameter name="fill-opacity">0.2</sld:CssParameter>`

I think this is connected somehow.

**Comment by KaiVolland** [comment]
I tackle this now.

**Comment by KaiVolland** [comment]
Currently we don't have seperate opacity for the fill-color in the `geostyler-style`. We just have `color` and `opacity` in the `BaseSymbolizer`.

So currently there is no way to specify the transparency of the fill color but keep a full opaque outline. I'll add the missing properties to the `MarkSymbolizer` in geostyler-style.

**Comment by KaiVolland** [comment]
The current version of `geostyler-style` (v1.2.1) has no `fill-opacity` property. The following PR introduces it:

https://github.com/terrestris/geostyler-style/pull/130
