### ISSUE TITLE
RasterSymbolizer / RasterCalculator

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#935]
This issue is meant do discuss the wanted functionality to style raster data with the `GeoStyler`.

The recent approach to implement styling of raster data is to follow the [SLD definition for the RasterSymbolizer](https://docs.geoserver.org/stable/en/user/styling/sld/reference/rastersymbolizer.html).

***
#### I don't like the SLD approach
I'm not experienced with it, but if i got i right, i don't want to use the concept of `SLD` in the GeoStyler.
1. :small_red_triangle_down:  The approach of the `GeoStyler` is to style a geographic dataset. This can be vector **OR** raster data. Not both at a time. So we don't want to mix as it is possible in SLD.
2. :small_red_triangle_down: The SLD `RasterSymoblizer` allows some kind of filtering inside. This is against the current concepts of the `GeoStyler`, where the features/pixels to style like this or that are filtered outside of the symbolizer.

***
#### Raster Calculator
As we discussed in 2017/18 an implementation of a Calculator for the PixelColor would be very cool.

The idea is to keep the current layout for a `Rule` but replace the `Filter` with a `Calculation(tbd)`. The Render would be just a square with the fill color.

The `Calculation` should be configurable via UI components. We could reuse some of #929 but i would like to do extend this with "real" calculation. 

Every pixel has n bands. Every band has a numeric value so it should be possible to calculate a value for r, g, b and with a mathematical function. First approach could be one `Textfield` each.

Pseudo example:
```js
const inputPx = {
  aBand: 11,
  bBand: 123,
  cBand: 23,
  dBand: 232
};
const r = inputPx.aBand * 2;
const g = inputPx.bBand / 3;
const b = inputPx.aBand + inputPx.dBand;
const a = Math.log(inputPx.cBand);

const outputPixel = rgba(r, g, b, a);
```

Current concerns about the Raster Calculator:
1. Engineering a featurecomplete static syntax for the functions. 
2. Translation to SLD. (Translation to OL on the other hand should be easy.)
3. Evaluation of mathematical calculation. (`eval`? :fearful: )

I hope we can start a discussion here. Love to here all your thoughts.
@terrestris/core 
@terrestris/devs 
@neteler 
@chrismayer

**Comment by jansule** [comment]
> 3. Evaluation of mathematical calculation. (`eval`? fearful )

We should find a way to serialize the calculation. IMHO using `eval` is not a nice approach. There, I would rather suggest taking a look at [mapbox expressions](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-math) which already provide a syntax for serializing mathematical functions.

geoserver provides a set of functions for this purpose as well ([see here](https://docs.geoserver.org/stable/en/user/filter/function_reference.html#math-functions)).

It would definitely be a lot of work to update the parsers but I think this would be a cleaner approach.

**Comment by jansule** [comment]
> #### I don't like the SLD approach
> I'm not experienced with it, but if i got i right, i don't want to use the concept of `SLD` in the GeoStyler.
> 
> 1. small_red_triangle_down  The approach of the `GeoStyler` is to style a geographic dataset. This can be vector **OR** raster data. Not both at a time. So we don't to mix as it is possible in SLD.

I think the general idea behind this is to be able to create a single style object/document that contains all information for a complete map "layout". This could include a basemap, and multiple overlays. Thus, a mix of raster and vector layers.

This approach gives users a lot of power, and it is up to them to decide what makes sense. BTW, mixing vector and raster styles is possible in `SLD` and `mapbox`.

I am not sure, if we should limit users in this regard.

> 2. small_red_triangle_down The SLD `RasterSymoblizer` allows some kind of filtering inside. This is against the current concepts of the `GeoStyler`, where the features/pixels to style like this or that are filtered outside of the symbolizer.

Just to give a little more information on this: It is possible to define so called `colorMap`s that change the colors of a band based on their value. This allows creating false color composites (e.g setting color values for DEMs). In some way this could be seen as a filter as we set colors for certain value (ranges).

**Comment by KaiVolland** [comment]
>I think the general idea behind this is to be able to create a single style object/document that contains all information for a complete map "layout".

IMHO That is not the focus of the `GeoStyler`

**Comment by KaiVolland** [comment]
We decide to merge the current approach of SLD-Raster integration into the master and develop the Calculator, too. In the future there might be bigger changes to the existing raster-code.
