### ISSUE TITLE
GeoServer Plugin

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#985]
### Description:
We want to develope a `GeoServer`-plugin that includes the `GeoStyler` UI directly in the `GeoServer` (wicket) UI.

**Comment by ahennr** [comment]
@hwbllmnn continues on this by introducing a new GeoServer community module , see https://github.com/geoserver/geoserver/pull/3607

:+1: :top:

**Comment by hwbllmnn** [comment]
The GeoServer core fixes and the community modules are merged now, thanks. There's still some issues left as mentioned in the MR, but I'm closing this for now.
