### ISSUE TITLE
Serialize filter expressions

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/geostyler#996]
## FEATUREREQUEST

We need to find a way to serialize [Filter expressions](https://docs.geoserver.org/stable/en/user/styling/sld/reference/filters.html#filter-expressions), e.g. transformation function and mathematical function for the RasterCalculator #935.

As we're close to the mapbox syntax we should make use of theses expressions: https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-math

**Comment by glenselle** [comment]
We are in need of creating a filter like so:
```xml
  <Or>
    <PropertyIsLike>
      <Function name="strMatches">
        <PropertyName>year</PropertyName>
        <Literal>^( )??2019,.*</Literal>
      </Function>
      <Literal>true</Literal>
    </PropertyIsLike>
    <PropertyIsLike>
      <Function name="strMatches">
        <PropertyName>year</PropertyName>
        <Literal>.*,( )??2019( )??,.*</Literal>
      </Function>
      <Literal>true</Literal>
    </PropertyIsLike>
  </Or>
```
I attempted to do the following, hoping it would just insert index `1` as the contents of the tag at index `0`. I believe this issue is designed to support filter expressions, which would include `Function` tags. But in the interim, would it be easy to add support for just a string version of the filter? Or is this already possible and I'm just doing it wrong? I would be willing to submit a PR to add support for this if you think it wouldn't be that hard to add support for this.
```javascript
filter: ['||',
    ['*=', '<Function name="strMatches"><PropertyName>year</PropertyName><Literal>^( )??2019,.*</Literal></Function><Literal>true</Literal>'],
    ['*=', '<Function name="strMatches"><PropertyName>year</PropertyName><Literal>.*,( )??2019( )??,.*</Literal></Function><Literal>true</Literal>']
],
```

**Comment by glenselle** [comment]
I've created a PR which demonstrates what I think could work as a stopgap before filters are natively supported: https://github.com/terrestris/geostyler-sld-parser/pull/195

**Comment by KaiVolland** [comment]
Hey @glenselle, appreciate that you'd like to support the project.

Instead of using xml-strings in the geostyler-filter a function expression could look like this:

```ts
['strMatches', PROPERTY_NAME, REGULAR_EXPRESSION]
```
…for your example:
```ts
['||',
  ['*=',
    ['strMatches', 'year', '^( )??2019,.*'],
    'true'
  ],
  ['*=',
    ['strMatches', 'year', '.*,( )??2019( )??,.*'],
    'true'
  ]
]
```

Would you be willing to provide a PR for this [here](https://github.com/terrestris/geostyler-style)? This might last longer than the stopgap.

To do so, you'd have to add a definition for the function expressions to the `geostyler-style`.

```ts
/**
 * The possible operators used for functional operations.
 */
export type FunctionOperator = 'strMatch';
```
… and a defintion for the `strMatches` function itself (see above).

Then you just have to adjust the parsers you need (e.g [SLD](https://github.com/terrestris/geostyler-sld-parser) to read and write the function properly.
Almost as you did in: https://github.com/terrestris/geostyler-sld-parser/pull/195

**Comment by KaiVolland** [comment]
I'll try to do the need steps for the `geostyler-style` now.

**Comment by KaiVolland** [comment]
Two things are missing:
- [ ] `geostyler-cql-parser` can handle the function expressions
- [ ] UI for editing function expressions (WIP #1048)

**Comment by hwbllmnn** [comment]
CQL parser part is implemented in terrestris/geostyler-cql-parser/pull/56

**Comment by glenselle** [comment]
Thanks for making this happen! Works great!

**Comment by drodenberg** [comment]
Hi, I'm currently trying to pass this filter [
      '*=',
      ['FN_strMatches', 'year', /^( )??2019,.*/],
      true
    ]

along to my sld but it translates that array with 'FN_strMatches' to the property name. How am I supposed to get that to add a function xml tag?

**Comment by jansule** [comment]
Hi @drodenberg, thanks for noticing us. Which version of `geostyler` and `geostyler-sld-parser` are you using?

**Comment by jansule** [comment]
The error might be due to the Filter not being exactly as described in [geostyler-style](https://github.com/terrestris/geostyler-style/blob/master/index.d.ts#L51-L55).

Could you try following filter expresssion and check if it works?

```
['||',
      ['*=',
        ['FN_strMatches', 'year', '^( )??2019,.*'],
        true
      ],
      ['*=',
        ['FN_strMatches', 'year', '.*,( )??2019( )??,.*'],
        true
      ]
    ]
```

Changed `strMatches` to `FN_strMatches` and `'true'` to `true`.

**Comment by drodenberg** [comment]
So that definitely got me a lot closer. My function is adding the `wildcard` property to the PropertyIsLike tag. I think that's not allowing the regex to execute correctly. Do you know how you guys are able to not include that in the `*=` notation?

**Comment by drodenberg** [comment]
Thanks a ton! That worked!
